<?php

namespace EMC\FileinputBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * This is the class that validates and merges configuration from your app/config files.
 *
 * To learn more see {@link http://symfony.com/doc/current/cookbook/bundles/configuration.html}
 */
class Configuration implements ConfigurationInterface
{
    /**
     * {@inheritdoc}
     */
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder();
        $rootNode = $treeBuilder->root('emc_fileinput');
        
        $rootNode
            ->children()
                ->scalarNode('file_class')->isRequired()->cannotBeEmpty()->end()
                ->arrayNode('providers')
                    ->children()
                        ->arrayNode('vimeo')
                            ->children()
                                ->scalarNode('client_id')->isRequired()->cannotBeEmpty()->end()
                                ->scalarNode('client_secret')->isRequired()->cannotBeEmpty()->end()
                                ->scalarNode('access_token')->end()
                                ->scalarNode('scope')->cannotBeEmpty()->defaultValue('private interact create edit upload delete public')->end()
                                ->arrayNode('whitelist')
                                    ->prototype('scalar')
                                    ->end()
                                ->end()
                                ->arrayNode('settings')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->enumNode('license')
                                            ->values(array('by','by-sa','by-nd','by-nc','by-nc-sa','by-nc-nd','cc0'))
                                        ->end()
                                        ->arrayNode('privacy')
                                            ->children()
                                                ->enumNode('view')
                                                    ->values(array('anybody','nobody','contacts','password','users','unlisted','disable'))
                                                ->end()
                                                ->booleanNode('download')
                                                    ->defaultFalse()
                                                ->end()
                                                ->booleanNode('add')
                                                    ->defaultFalse()
                                                ->end()
                                                ->enumNode('comments')
                                                    ->values(array('anybody', 'nobody','contacts'))
                                                ->end()
                                                ->enumNode('embed')
                                                    ->values(array('public','private','whitelist'))
                                                ->end()
                                            ->end()
                                        ->end()
                                        ->scalarNode('password')->end()
                                        ->booleanNode('review_link')->end()
                                        ->scalarNode('locale')->end()
                                        ->arrayNode('embed')
                                            ->children()
                                                ->arrayNode('buttons')
                                                    ->children()
                                                        ->booleanNode('like')
                                                            ->defaultTrue()
                                                        ->end()
                                                        ->booleanNode('watchlater')
                                                            ->defaultTrue()
                                                        ->end()
                                                        ->booleanNode('share')
                                                            ->defaultTrue()
                                                        ->end()
                                                        ->booleanNode('embed')
                                                            ->defaultTrue()
                                                        ->end()
                                                        ->booleanNode('hd')
                                                            ->defaultTrue()
                                                        ->end()
                                                        ->booleanNode('fullscreen')
                                                            ->defaultTrue()
                                                        ->end()
                                                        ->booleanNode('scaling')
                                                            ->defaultTrue()
                                                        ->end()
                                                    ->end()
                                                ->end()
                                                ->arrayNode('logos')
                                                    ->children()
                                                        ->booleanNode('vimeo')
                                                            ->defaultTrue()
                                                        ->end()
                                                        ->arrayNode('custom')
                                                            ->children()
                                                                ->booleanNode('active')
                                                                    ->defaultTrue()
                                                                ->end()
                                                                ->booleanNode('sticky')
                                                                    ->defaultTrue()
                                                                ->end()
                                                                ->scalarNode('link')->end()
                                                            ->end()
                                                        ->end()
                                                    ->end()
                                                ->end()
                                                ->booleanNode('playbar')
                                                    ->defaultTrue()
                                                ->end()
                                                ->booleanNode('volume')
                                                    ->defaultTrue()
                                                ->end()
                                                ->scalarNode('color')->end()
                
                                                ->arrayNode('title')
                                                    ->children()
                                                        ->enumNode('owner')
                                                            ->values(array('user','show','hide'))
                                                        ->end()
                                                        ->enumNode('portrait')
                                                            ->values(array('user','show','hide'))
                                                        ->end()
                                                        ->enumNode('name')
                                                            ->values(array('user','show','hide'))
                                                        ->end()
                                                    ->end()
                                                ->end()
                                            ->end()
                                        ->end()
                
                                        ->arrayNode('rating')
                                            ->children()
                                                ->arrayNode('mpaa')
                                                    ->children()
                                                        ->enumNode('rating')
                                                            ->values(array('g','pg','pg13','r','nc17','x'))
                                                        ->end()
                                                        ->enumNode('reason')
                                                            ->values(array('at','n','bn','ss','sl','v'))
                                                        ->end()
                                                    ->end()
                                                ->end()
                                                ->arrayNode('tv')
                                                    ->children()
                                                        ->enumNode('rating')
                                                            ->values(array('tv-y','tv-y7','tv-y7-fv','tv-g','tv-pg','tv-14','tv-ma'))
                                                        ->end()
                                                        ->enumNode('reason')
                                                            ->values(array('d','fv','l','ss','v'))
                                                        ->end()
                                                    ->end()
                                                ->end()
                                            ->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
